---
- name: Harden Operating System
  hosts: all
  become: yes
  tasks:
    - name: remove unnecessary packages
      yum:
        name:
          - xinetd
          - ypserv
          - tftp-server
          - telnet-server
          - rsh-server
        state: absent
...
